- hosts: all
  become: true
  roles:
    - test-connectivity
    - install-docker-composer
    - update-server
    - install-docker
    - yolo-client
    - yolo-backend
    - git-deploy
    - setup-docker-containers
    
