---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client-container
          image: rajabibraz/yolo-client:v1.0
          imagePullPolicy: Always
          env:
            - name: CHOKIDAR_USEPOLLING
              value: 'true'
            - name: stdin_open
              value: 'true'
            # - name: REACT_APP_API_URL
            #   value: http://backend-service:5000
          tty: true

          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: LoadBalancer
  selector:
    app: client
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
