---
# tasks file for build-backend
- name: Build backend docker image
  docker_image: 
     name: backend-image
     source: build 
     build:
        path: "{{ dockerfile_path}}"
        pull: yes

  register: image

- name: Check image
  debug:
    var : image