---
# tasks file for install-docker and its dependencies



    - name: Install pip3
      become: true
      apt:
        name: python3-pip
        state: present

    - name: Install docker
      become: true
      pip:
        name: docker==6.1.3
        state: present
   

